name: 'Audit'
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'main'
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run audit
        run: DAFNY=dafny/dafny scripts/audit.sh
      - name: Commit audit
        uses: EndBug/add-and-commit@v9
        with:
          author_name: John Tristan
          author_email: mail@example.com
          message: 'Adding audit log'
          add: 'audit.log'
