name: 'Build Java'
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'main'
jobs:
  build-java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: bash scripts/prep.sh
      - run: DAFNY=dafny/dafny TARGET_LANG=java bash scripts/build.sh
      - run: build/java/run.sh
