name: 'Check formatting'
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'main'
jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - run: bash scripts/prep.sh
      - run: DAFNY=dafny/dafny bash scripts/checkformat.sh
