name: 'Run Python tests'
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'main'
jobs:
  test-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: bash scripts/prep.sh
      - run: DAFNY=dafny/dafny TARGET_LANG=py bash scripts/test.sh
