name: 'Verify DafnyVMCTrait.dfy'
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'main'
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - run: bash scripts/prep.sh
      - run: cp src/DafnyVMCTrait.dfy.log src/DafnyVMCTrait.dfy_.log
      - run: DAFNY=dafny/dafny bash scripts/sampcert.sh
      - run: cat src/DafnyVMCTrait.dfy.log
      - run: diff src/DafnyVMCTrait.dfy.log src/DafnyVMCTrait.dfy_.log
