name: 'Verify proofs'
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'main'
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - run: bash scripts/prep.sh
      - run: DAFNY=dafny/dafny bash scripts/verify.sh
