name: 'Verify proofs and test samplers'
on:
  workflow_dispatch:
  pull_request:
jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: wget https://github.com/dafny-lang/dafny/releases/download/v4.2.0/dafny-4.2.0-x64-ubuntu-20.04.zip
      - run: unzip dafny-4.2.0-x64-ubuntu-20.04.zip
      - run: export DAFNY=dafny/dafny
      - run: pwd
      - run: ls
